.gitignore, defaults/main.yml, handlers/main.yml, tasks/fix-cat1.yml, tasks/fix-cat2.yml, tasks/fix-cat3.yml, tasks/main.yml, tasks/prelim.yml, tests/ansible.cfg, tests/test.yml, vars/main.yml
Major changes:
* Finished updating task numbering to V1R1 STIG content.
* Removed audit tasks
* Added variables for each STIG ID so each item can be enabled/disabled via the corresponding variable
* Made some style changes and cleaned up some items that were not working on CentOS 7
* Started to organize tasks into related blocks to apply conditionals and tags to the entire block
=> Updates to the STIG role

README.md, defaults/main.yml, tasks/fix-cat2.yml
With this PR, one will be able to configure whether or not to use `firewalld` or `iptables` (our systems use iptables, so we need this).
=> Firewall Service - Ability to have iptables

tasks/fix-cat1.yml, tasks/fix-cat2.yml
Modify RHEL-07-010300 from using tag `sshd` to `ssh`.
Modify RHEL-07-040110 to include `ssh` tag.
=> Adjust ssh tags to match global format

README.md, defaults/main.yml, tasks/fix-cat2.yml
Minor changes to make play compatible with V1R2 of the RHEL7 STIG released on July 28, 2017.
=> STIG v1r2 updates

tasks/fix-cat2.yml
Identified sshd STIG with old `validate` command.  
Correcting `sshd -t -f %s` to `/usr/sbin/sshd -t -f %s`.
=> correct-sshd-validation (RHEL-07-010470)

tasks/fix-cat2.yml
The fix for this rule is to modify /etc/pam.d/sshd or /etc/ssh/sshd_config. When both are modified I observed duplicate lastlog lines being printed.
=> Apply one fix for sshd lastlog

tasks/fix-cat2.yml
This rule could not be skipped since conditionals depended on a registered variable.
=> Block kdump tasks to require, disable, or skip

defaults/main.yml
While running some tests I noticed the UMASK setting in /etc/login.defs was being set to the number 63 instead of the expected 077.
Looking into it, python treats all numbers that begin with '0' as octal notation; '077' in octal is 63 in decimal.
Quoting this value (i.e., changing it into a string) resolves this issue.
=> Convert rhel7stig_login_defaults.umask to string value.

filter_plugins/filters.py
Per #58 and the comments on #23 some recent systems still have slightly older versions of passlib installed by default. i.e. RHEL7 still uses python-passlib-1.6.5
Updated the filter plugin to support back to 1.5 but it could probably work with as old as 1.4 if necessary. Made some other minor updates as well:
* updated to support older passlib versions back to 1.5
* updated to use the hash() and using() methods on 1.7+ so that the plugin won't die once encrypt() is fully removed
* removed code to generate random salt as passlib does this by default
* removed unneeded python libraries that were used in random salt generation code
* use kwargs to pass user specified values for salt and rounds to the encrypt() or hash() methods
* set default rounds to 25000 to match the default value passlib …
=> grub2_hash support for older (<1.7) passlib versions

tasks/fix-cat2.yml
Bad syntax for `modprobe.d` blacklist entry
Fixes #62
=> Fix usb-storage blacklist syntax

tasks/prelim.yml
As 040410 and 040420 are about ssh host key pairs, it should match the intent and produce fewer side effects if we restrict looking for host keys in /etc/ssh and of the format ssh_host*_key and ssh_host*_key.pub.
=> Adjust ssh key paths to /etc/ssh and valid file patterns

tasks/audit_command.yml, tasks/audit_file.yml, tasks/audit_system_call.yml, tasks/fix-cat2.yml
audit loop fixes:
- audit both 32 and 64-bit system calls
- fix -EACCES error-causing typo
- commands audited migrated to audit_commands.yml
- eliminated need for separate "create" parameter
- reformatted code to match guidelines
Please merge rather than squash.
=> Audit fixup

defaults/main.yml, tasks/fix-cat2.yml
Shouldn't cause any harm, as it appears the IPSec service won't be enabled automatically. By default, libreswan would be removed. If the site decides they need IPsec and enable that variable, libreswan will be installed, but won't run by default.
The only way a site gets a finding is if they:
- set `rhel7stig_ipsec_needed` to true and apply the role
- manually enable the service (not a part of this role)
- fail to notify their ISSO of any exceptions
=> Working on RHEL-07-040820.

defaults/main.yml, handlers/main.yml, tasks/fix-cat1.yml, tasks/prelim.yml, templates/etc_default_grub.j2, vars/main.yml
These changes remediate a system that was not built with fips=1 on the installer command line.
Please don't squash.
=> Fix OS-level FIPS crypto

README.md, defaults/main.yml, tasks/fix-cat1.yml
`lftpd` was replaced with `vsftpd`.
=> Updating RHEL-07-040690 to V1R4

tasks/fix-cat3.yml
also fixed whitespace to be consistent with examples in default limits.conf
=> limits.conf: avoid replacing comment lines

defaults/main.yml, tasks/fix-cat2.yml
Can remove the `savlog` command, but all sites would have to set it to their preferred command. If someone can tell me what the CLAM equivalent would be, I can edit the default.
=> Implementing 032010

defaults/main.yml, tasks/fix-cat2.yml
Only setting permissions if the home directory's stat results indicate group `w` or other `rwx`.
=> Fixing 122

tasks/fix-cat2.yml
If `nosuid` is missing from `/home` mount options, and `/home` is a separate filesystem, add `nosuid` to the current mount options.
This may change the `/home` options even if it's NFS-mounted, which falls under 021020. But there's no distinction made in 021000 for the type of filesystem. Since the only way to avoid a finding on 021000 (if applicable) is to have `/home` be a part of `/`, I'm reading this as "add the `nosuid` option to `/home`, regardless of its physical location".
=> Implementing RHEL-07-021000

defaults/main.yml, tasks/fix-cat2.yml
Will probably need to be rebased if James' local_mounts consolidation goes in first. Doesn't exactly match the STIG check, since it looks through `/etc/fstab`, and this looks through active mounts.
=> Implementing 021020 and 021021

tasks/fix-cat1.yml
this prevents attempting to traverse /proc and similar
=> add -xdev to find commands

tasks/fix-cat1.yml, tasks/fix-cat2.yml, tasks/main.yml
Starting in ansible 2.5, the use of jinja tests as filters has been
deprecated.
https://docs.ansible.com/ansible/2.5/porting_guides/porting_guide_2.5.html#jinja-tests-used-as-filters
This change keeps the syntax compatible with ansible 2.4 while fixing
the deprecation errors that would otherwise appear when running the
role under ansible 2.5+.
I've tested these changes against ansible versions 2.5.0-2.el7 and 2.4.2.0-2.el7
=> rewrite deprecated jinja tests used as filters

.travis.yml, defaults/main.yml, tasks/fix-cat1.yml, tests/extra_vars_travis.yml, tests/extra_vars_travis_idempotence.yml, vars/main.yml
This starts implementation of the proposal I made in https://github.com/MindPointGroup/RHEL7-STIG/issues/119#issuecomment-381254864
This implements the complexity-high and distruption-high concepts, vars, and tags, with an example of each.
Proposal quoted:
> Here's my proposal.
> The scap-security-guide project labels their remediation tasks with 3 categories: severity, complexity, and disruption.  It seems like a good approach to me:
> 
> - I suggest we tag items requiring manual review as `complexity-high` and add a conditional on `rhel7stig_complexity_high: default(no)`.
> - I suggest we tag items that can break a system as `disruption-high` and add a conditional on `rhel7stig_disruption_high: default(no)`.
> 
> We can then add later `disruption-medium` and `disruption-low` for tasks …
=> Proof-of-concept: handling of disruptive and complex tasks

defaults/main.yml
From tasks/fix-cat1.yml:
```- name: |
"HIGH | RHEL-07-010480 | PATCH | Systems with a Basic Input/Output System (BIOS) must require authentication upon booting into single-user and maintenance m
odes."
"HIGH | RHEL-07-010490 | PATCH | Systems using Unified Extensible Firmware Interface (UEFI) must require authentication upon booting into single-user and ma
intenance modes."
lineinfile:
dest: /etc/grub.d/40_custom
insertafter: EOF
regexp: "{{ item.regexp }}"
line: "{{ item.line }}"
with_items: "{{ rhel7stig_boot_password_config }}"
notify: make grub2 config
when: rhel_07_010480 or rhel_07_010490 <<<<<<<<<<
tags:
- RHEL-07-010480
- RHEL-07-010490
- grub
- bootloader
```
=> Fix incorrect comments for grub

tasks/fix-cat1.yml, tasks/fix-cat2.yml, tasks/prelim.yml
boot= needs to point to /boot, not /boot/efi.  The STIG says to point to /boot/efi, which breaks system boot.
2 other minor items included.
=> Fix FIPS for EFI systems, et al.

tasks/fix-cat2.yml
There is variation in the groupname, change to id referral to remove variation
`yum grouplist hidden id | grep X`
`X Window System (x11)`
`Legacy UNIX Compatibility (legacy-unix)`
`Legacy X Window System Compatibility (legacy-x)`
=> Change yum group to x11 id value

defaults/main.yml, tasks/fix-cat2.yml
The check content says to run:
grep -i tmout /etc/bashrc /etc/profile.d/*
With this change, that check would pass.
Also clean up the version in /etc/profile
=> TMOUT: pass STIG check as written

defaults/main.yml, handlers/main.yml, tasks/fix-cat1.yml, tasks/fix-cat2.yml, tasks/fix-cat3.yml, vars/main.yml
In conjunction with #161, these changes allow the role to successfully run in a kickstart "%post" script to STIG a system at provisioning time.
=> feature: run role in a chroot environment

defaults/main.yml, handlers/main.yml, tasks/fix-cat1.yml, tasks/fix-cat2.yml, tasks/fix-cat3.yml, vars/main.yml
after these changes, the role can be run on unprivileged containers running systemd (such as the rhel7-init container) by setting:
```
rhel7stig_system_is_container: yes
```
The role can also be run on unprivileged non-systemd-running containers by additionally setting:
```
rhel7stig_system_is_chroot: yes
```
=> feature: unprivileged container support

defaults/main.yml, tasks/fix-cat2.yml
rebase of #157 
updated new variable name to `rhel7stig_ssh_session_timeout` to mirror existing `rhel7stig_shell_session_timeout`
=> ssh: allow custom session timeout value

.gitignore, defaults/main.yml, tasks/fix-cat2.yml
- RHEL-07-010150: "dcredit" -> "ocredit" in the fix text
- RHEL-07-010200: reference both password-auth and system-auth instead of system-auth-ac
- RHEL-07-010270: references both password-auth and system-auth instead of system-auth-ac, "pam_unix.so"->"pam_pwhistory.so"
- RHEL-07-010320: references both password-auth and system-auth instead of system-auth-ac
- "unlock_time=604800" -> "fail_interval=900 unlock_time=900"
- RHEL-07-010330: references both password-auth and system-auth instead of password-auth-ac and system-auth-ac
- "unlock_time=604800" -> "unlock_time=900"
- RHEL-07-010350: non-compliant configs allowed in commented-out lines
- RHEL-07-010430: if the required config is commented, it is a finding
- RHEL-07-020110: stop autofs in addition to disable
- Also made some updates …
=> STIG v2r1 updates - batch 2

tasks/prelim.yml, tests/docker/molecule/default/playbook-local.yml, tests/docker/molecule/default/playbook.yml
Description of PR
Fixes Deprecation warnings with the upgrade to Ansible 2.7.
Specifically it removes the loop that is no longer needed with the upgrade.
Type of change
Feature Pull Request
Fixes an issue
Fixes following Deprecation Warning
[DEPRECATION WARNING]: Invoking "yum" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying name: {{ item }}, please use name: [u'snappy', u'snappy- devel', u'zlib', u'zlib-devel', u'hwloc', u'gcc', u'lzo', u'lzo-devel', u'python', u'make'] and remove the loop. This feature will be removed in version 2.11. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
=> Fixes deprecation warnings that are associated with loops using yum

defaults/main.yml, tasks/audit_command.yml, tasks/fix-cat1.yml, tasks/fix-cat2.yml
Summary
- Fixes 010290 which was failing SCAP checks due to password-auth not being remediate for the presence of nullok
- Add a capability to pass 030300
- Fixed a dup auditd for 030740 and made it so that rule would pass. It _was_ failing due to the presence of `perm-x` which is not part of the official guidance.
=> Some light updates

tasks/fix-cat2.yml
identical change to https://github.com/MindPointGroup/RHEL6-STIG/pull/137
=> reposition pam_faillock.so, allow domain auth to succeed

defaults/main.yml, tasks/fix-cat1.yml, tasks/fix-cat2.yml, tasks/fix-cat3.yml
These fixes/changes are mainly to support the documentation generation that is in the `migrate_ah_docs` branch 725b2bf.
The changes split by atomic commits so it is easy to review. There are name updates to bring them in line with the standard, addition of a name parameter so there are no bare `block` statements, and the last change makes the RHEL-07-010260 task be a disruption-high item instead of just being disabled by default since the reasoning for disabling it was that it has a high chance of locking out users.
Once this is merged I can work on getting the doc generation merged in and running for the devel branch.
=> Fix up naming, block statements, and make 010260 use disruption-high mode for doc gen

.travis.yml, molecule/docker/Dockerfile
Red Hat is migrating their container registry from `registry.access.redhat.com` to `registry.redhat.io` and going forward will require auth even for pull operations. This updates the Travis config to account for that.
=> update travis to pull from new RH registry loc with auth

tasks/fix-cat2.yml
change /etc/pam.d/passwd to /etc/pam.d/system-auth
Description
Use of a complex password helps to increase the time and resources required to compromise the password. Password complexity, or strength, is a measure of the effectiveness of a password in resisting attempts at guessing and brute-force attacks. "pwquality" enforces complex password construction configuration and has the ability to limit brute-force attacks on the system.
Solution
Configure the operating system to use "pwquality" to enforce password complexity rules.
Add the following line to "/etc/pam.d/system-auth" (or modify the line to have the required value):
password required pam_pwquality.so retry=3
Note: The value of "retry" should be between "1" and "3".
=> V2R1 Rule change for RHEL-07-010119

tasks/fix-cat2.yml
This pull reqeuest fixes the rules below to be compliant with V2R1 and V2R2, removes '-F perm=x' from audit rules.
Fix rules for:
RHEL-07-030560
RHEL-07-030570
RHEL-07-030580
RHEL-07-030590
RHEL-07-030640
RHEL-07-030680
RHEL-07-030690
RHEL-07-030710
RHEL-07-030720
RHEL-07-030750
RHEL-07-030760
RHEL-07-030770
RHEL-07-030780
RHEL-07-030800
RHEL-07-030810
=> Remove '-F perm=x' for compliance with V2R1

tasks/fix-cat2.yml
Changes to be compliant with changed RHEL-07-030360 in V2R1 and V2R2
**New Text since V2R1:**
Configure the operating system to audit the execution of privileged functions.
Add or update the following rule in "/etc/audit/rules.d/audit.rules":
Note: The rules are duplicated to cover both 32-bit and 64-bit architectures. Only the lines appropriate for the system architecture must be configured.
-a always,exit -F arch=b32 -S execve -C uid!=euid -F euid=0 -k setuid
-a always,exit -F arch=b64 -S execve -C uid!=euid -F euid=0 -k setuid
-a always,exit -F arch=b32 -S execve -C gid!=egid -F egid=0 -k setgid
-a always,exit -F arch=b64 -S execve -C gid!=egid -F egid=0 -k setgid
The audit daemon must be restarted for the changes to take effect.
**Old Text: in V1R4**
Configure the operating system to …
=> audit suid/sgid executions - Fix RHEL-07-030360 for V2R1 and V2R2

defaults/main.yml, tasks/fix-cat2.yml
also avoid munging repos.  Failure occur if the optional-rpms repo is not available even if it's not needed, when it's explicitly requested.
fixes #204
=> Don't enable yum-cron by default

handlers/main.yml, tasks/prelim.yml
if the keys don't exist, "sshd -t -f %s" fails
remove the keys at the end to allow the normal key generation process to take place
=> temp sshd keys for config validation

tasks/prelim.yml
=> STIG requires targeted policy, not mls

tasks/fix-cat3.yml
If "pam_lastlog" is missing from "/etc/pam.d/postlogin" file, or the
silent option is present, this is a finding.
A compliant line is already placed by the role, but the DISA benchmark
is flagging another default line as non-compliant.
I'd appreciate any testing against existing setups; things worked fine for me w/ this change.
=> pam_lastlog: "silent" most not be present

defaults/main.yml
this makes the banner somewhat hard to read
The V2R2 benchmark badly tries to make sure that there is no extra text in the banner, and the "extra" line breaks cause a false positive rule failure.  This works around that by removing our extra line breaks.
=> remove banner line breaks to satisfy benchmark

defaults/main.yml, handlers/main.yml
The DISA benchmark V2R2 fails 3 rules (1 high, 2 medium) if both UEFI
and BIOS paths are not present.
Even so, this only fixes things for RHEL 7.5 or earlier.  The DISA benchmark does not recognize 7.6 as a supported release, causing a failure of these 3 rules, plus the "supported OS" rule.  You can workaround that one by setting '7.6' to '7.5' in /etc/redhat-release, but I'm not going to automate that here -- besides, it would be overwritten by the 'file checksum must match RPM value'
=> sync BIOS and UEFI grub config paths

tasks/fix-cat2.yml
https://vaulted.io/library/disa-stigs-srgs/red_hat_enterprise_linux_7_security_technical_implementation_guide/V-72191?version=V1R4&compareto=V2R2
resolves comment on #174
=> audit: kmod still requires "-f perm=x" in V2R2

defaults/main.yml
This helps makes a system as compliant as possible when using `rhel7stig_disruption_high: yes`
=> enable aide mail in disruption-high mode

tasks/fix-cat2.yml
RHEL-07-031010 references a requirement to prevent `imrelp` in `/etc/rsyslog.conf` that is not currently present.  I also added space following the `#` for readability purposes.
=> adds imrelp to rhel-07-031010 & space following #

local.yml
ansible_python_interpreter is already set automatically by ansible
exactly as this line attempts to do
=> fix local.yml for ansible-2.4

tasks/fix-cat1.yml
as of V2R1, the check content and fix content match in requiring the
absence of the tftp-server, not the tftp package -- previously, the fix
content said to get rid of the tftp package
related #174
=> remove only tftp-server

tasks/fix-cat1.yml
previously this task failed if a failing package name had whitespace
=> quote packages names

tasks/fix-cat2.yml
This is what the DISA benchmark looks for as of V2R4.
If you really wanted to go overboard, you could use /usr/bin/true, but
it'd fail the benchmark.
fixes: #270
=> disable usb-storage /bin/true

tasks/audit_command.yml
The DISA benchmark now complains without the filter, so add it back
unconditionally.  I did not check whether SSG still complains about
its presence.
=> filter anonymous kmod operations

tasks/parse_etc_passwd.yml
This speeds up run time and reduces screen noise when parsing the `/etc/passwd` file.
=> parse_passwd: list comprehension instead of loop

tasks/fix-cat1.yml
ansible tries to set SELinux contexts on these files, which the
underlying fs does not support
fixes #249
related https://github.com/ansible/ansible/pull/59823
=> touch-create files on vfat efi partition

test_plugins/rhel7_stig_ansible_backport.py, test_plugins/rhel7_stig_jinja_compat.py
Ansible assumes these are in place and provided by jinja.
Also grabbed "contains" test from ansible-2.8, "just in case"
=> add compatability jinja tests

defaults/main.yml
RHEL-07-040500 is NTP related and not TFTP.
TFTP are covered by RHEL-07-040700 and 040720
=> Update main.yml informative comment change of appropriated

defaults/main.yml, tasks/prelim.yml
This is a quick fix to address https://github.com/MindPointGroup/RHEL7-STIG/issues/222.  I've validated that it successfully pulls the machine ID and uses it as the salt in the hash.
fixes #222
=> Changed grub salt to machine_id from ansible_facts.

defaults/main.yml, tasks/fix-cat2.yml
Set rhel7stig_using_uuid_fstab to true to mount the /home volume
by its UUID instead of device
=> Allow UUID home mounts

README.md
Per current documentation (https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#version-comparison) the "version_compare" test has been renamed to "version" as of Ansible 2.5.  Also minor updates to spelling, an update of the example to use the current "is" nomenclature, and fix test to "==".
=> Spelling and example syntax update

defaults/main.yml, tasks/fix-cat1.yml, tasks/fix-cat2.yml, tasks/main.yml, tasks/prelim.yml
These changes make it so that the RHEL7-STIG role can be run cleanly on RHEL 8.
=> enable role for RHEL 8

tasks/fix-cat2.yml
Set follow to false for the file module so it does not fail on recursive directory trees like the tests direcitory in this role.
Fixes #320
=> Change file operation to not follow symlinks

tasks/prelim.yml
If you run the rhel7-stig role with --tags sudoers the following tasks will fail do to the needed prelim task not being ran:
https://github.com/MindPointGroup/RHEL7-STIG/blob/9139806317745b7996a49e5c29fb6ff88272da79/tasks/fix-cat2.yml#L582-L606
Added missing tag to the dependent prelim task
=> Add sudoers tag to related prelim task

tasks/fix-cat1.yml
The RHEL-07-010491 task in fix-cat1.yml attempts to check/update `/boot/grub2/grub.cfg`, but this file does not exist on UEFI systems and the task fails. The old version of the role performed this task on `/etc/grub.d/01_users` which seems more proper since direct edits to grub.cfg are overwritten by `grub2-mkconfig`.
Signed-off-by: Dan Barr <dan@dbarr.com>
=> Fix RHEL-07-010491 grub superusers config

defaults/main.yml
RHEL-07-021031 task fails because the conditional `rhel7stig_world_write_files_owner_root` does not exist. In defaults/main.yml it's defined as `ol7stig_world_write_files_owner_root`; updating to fix the name and control # in the comment.
Sidebar: the preceding variable in the defaults, ol7stig_ipv4_tcp_invalid_ratelimit, isn't used anywhere in the role and probably could be removed, but I didn't do that in this PR.
Signed-off-by: Dan Barr <dan@dbarr.com>
=> Fix variable name

defaults/main.yml
The /etc/issue and /etc/issue.net banners shouldn't be dependent on GUI
Signed-off-by: Dan Barr <dan@dbarr.com>
=> Fix RHEL-07-010050 default enable/disable setting

templates/aide.conf.j2
Use syslog format for one line per timestamp for better external logger support (i.e. Splunk)
By default, aide logs are multi-line without timestamp making external logger parsing complex.
Each log output line has a timestamp
Tested locally with an instance using this repo, verified output logs are syslog format.
=> Syslog format by default

handlers/main.yml, tasks/fix-cat1.yml, tasks/post_remediation_audit.yml, tasks/prelim.yml
Currently, this role can break when used with Ansible 2.14 and later because of the use of the warn argument to suppress warning output has been removed. Ansible no longer displays these warnings as of version 2.11. These change simply remove the use of this argument when using the shell module in order to restore compatibility with newer versions of Ansible.
See this PR for more information on the deprecated warnings feature in Ansible: https://github.com/ansible/ansible/pull/70504
N/A
=> Remove use of deprecated shell module warnings feature in Ansible

ChangeLog.md, tasks/main.yml
Overall Review of Changes:
Improve password check for rule RHEL-07-010340 that sudo user must have a password or sudo will fail to work.
Issue Fixes:
https://github.com/ansible-lockdown/RHEL7-STIG/issues/428
Enhancements:
Only run if the playbook is not being run as a super user
How has this been tested?:
Manually
=> Improve sudo user password check

tasks/fix-cat2.yml, tasks/main.yml, tasks/pre_remediation_audit.yml, tasks/prelim.yml
These changes will try to correct some errors and incorporate multiple hints within Ansible tasks that I have encountered when running some checks with [Steampunk Spotter](https://steampunk.si/spotter/). 
The first change fixes the following error detected by the Spotter CLI:
```console
(.venv) user@ubuntu:~/UBUNTU22-CIS$ spotter scan --ansible-version 2.12 --display-level error .
Scanning...success. ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
------------------------------------------------------------------------
tasks/fix-cat2.yml:1108:9: ERROR: [E001] with_items is not a valid parameter in module ansible.builtin.package.
tasks/prelim.yml:55:9: ERROR: [E005] state is a required parameter in module ansible.builtin.package. …
```
=> Task validation fixes and rewrites (by Steampunk Spotter)

handlers/main.yml
Adds an additional condition to be satisfied in order for tasks to run for grub2 handlers
https://github.com/ansible-lockdown/RHEL7-STIG/issues/440
N/A
Tested against current version of RHEL7
=> Adding additional condition for rhel7stig_grub2_user_cfg for task

defaults/main.yml, tasks/fix-cat1.yml, tasks/fix-cat2.yml, tasks/prelim.yml
rule_021350 when set false caused failures.
Created discovery for system and default var removed
manually on bios and efi based systems
=> rhel7stig_boot_part variable now discovered

README.md, meta/main.yml, templates/audit/99_auditd.rules.j2
Issues addressed
galaxy_ng updates
#452 
#453 
Changes to meta and readme to address the changes in ansible galaxy NG
Manually
=> Feb 24 updates

tasks/parse_etc_passwd.yml
Overall Review of Changes:
Excludes non interactive shells listed in /etc/shells from being registered in the rhel7stig_passwd_file_audit variable
Issue Fixes:
https://github.com/ansible-lockdown/RHEL7-STIG/issues/462
Enhancements:
N/A
How has this been tested?:
tested code in separate task, results were as expected
=> Excluding non-interactive logins shells from being parsed

ChangeLog.md, defaults/main.yml, handlers/main.yml, site.yml, tasks/LE_audit_setup.yml, tasks/audit_only.yml, tasks/fix-cat1.yml, tasks/fix-cat2.yml, tasks/main.yml, tasks/parse_etc_passwd.yml, tasks/post_remediation_audit.yml, tasks/pre_remediation_audit.yml, tasks/prelim.yml, templates/etc/yum.repos.d/CentOS-Base.repo.j2, vars/audit.yml, vars/main.yml
- Improvements by moving to new workflow configurations
- New audit setup and standardization
- 021350 improvement
Please give an overview of how these changes were tested. If they were not please use N/A
=> Workflow audit

tasks/fix-cat1.yml, tasks/fix-cat2.yml
general updates
010020 labelled correctly
021350 layout updated
041010 reordered
020019 change case
PIpeline
=> Oct24 updated
