files/issue
tasks/audit-cat2.yml
tasks/fix-cat2.yml

Add support for:
RHEL-07-010040
RHEL-07-010090
RHEL-07-010100
RHEL-07-010110
RHEL-07-010120
RHEL-07-010130
RHEL-07-010140
RHEL-07-010150
RHEL-07-010160
RHEL-07-010200
RHEL-07-010210
RHEL-07-010220
RHEL-07-010230
RHEL-07-010240
RHEL-07-010250

Add CAT2 Password Requirements

---

README.md
defaults/main.yml
handlers/main.yml
tasks/audit-cat2.yml
tasks/fix-cat2.yml
vars/main.yml

Account for different time services

---

tasks/fix-cat1.yml

Merging in changes from @pdavies14

Updates to CAT 1 fixes

---

.travis.yml
defaults/main.yml
filter_plugins/filters.py
tasks/fix-cat2.yml
tests/Dockerfile.centos-7
tests/Dockerfile.rhel-7
tests/extra_vars.yml
tests/travis.yml

Testing on Travis CI with CentOS and RHEL7 container images.

Make travis work

---

filter_plugins/filters.py
tests/Dockerfile.centos-7
tests/Dockerfile.rhel-7

- Remove unneceassry imports
- Report an error istead of a stack trace if passlib is not installed
Fixes #21

Cleanup grub2_hash filter

---

tasks/fix-cat1.yml
tasks/fix-cat2.yml
tests/Dockerfile.centos-7

Validate command must use absolute path

---

tasks/fix-cat1.yml
tasks/fix-cat2.yml
tests/Dockerfile.centos-7

Merge ssh and travis build fixes into stable and cut a new release for Galaxy

merge ssh and travis fixes from devel

---

tasks/fix-cat2.yml
tasks/prelim.yml

- fix for #38 
- moved prelim task into task block in cat2 file

fix conditional issue with RHEL-07-040180 #38

---

README.md
defaults/main.yml
tasks/fix-cat1.yml
tasks/fix-cat2.yml
tasks/fix-cat3.yml
tasks/prelim.yml
tests/apply_role.yml

This is a work in progress branch for addition of CAT2 and CAT3 tasks as well as some clean up items and rework.

CAT2 and CAT3 task updates and clean up

---

filter_plugins/filters.py

use string encode() function for passlib salt parameter fixes #50

---

tasks/fix-cat3.yml
tests/ansible-redhat7-stig-progress.ckl

Good evening all.
I took a crack at resolving cat III issue RHEL-07-040530.
The implementation appears to be safe enough to run multiple times against the same system without adverse effects.
Please review and let me know if you have any concerns or changes I should make.

Rhel 07 040530

---

tasks/fix-cat2.yml
tasks/prelim.yml

Expanding missing owner and missing group searches to all local filesystems

---

README.md

README: update passlib requirement

---

tasks/fix-cat1.yml
tasks/fix-cat2.yml

Implementing RHEL-07-040720.
Modifying RHEL-07-040700 to install tftp and tftp server when required.

Implementing 040720.

---

tasks/fix-cat2.yml

fixes #92 (sudo remediations fail)

fix visudo path

---

defaults/main.yml
handlers/main.yml
tasks/fix-cat2.yml
tasks/prelim.yml

rebased version of #87 , based on feedback.
The big fix was using 25% for space_left, when I'd erroneously used the entire value previously.
Closes #87 
Please don't squash.

Audit config (rebase from #87)

---

tasks/fix-cat2.yml

This missed my earlier PR because I'd thought it was duplicated by mike's PRs and I dropped what I thought was duplicate.

encrypt audit record transport

---

tasks/fix-cat2.yml

anchor audit regex to start of line

---

defaults/main.yml
tasks/fix-cat2.yml

May have misinterpreted what a good AUDIT task would be.

Implementing RHEL-07-020270

---

tasks/fix-cat1.yml
tasks/fix-cat2.yml

V1R4 ssh updates

---

tasks/fix-cat2.yml
tasks/prelim.yml

Let me know if you want separate PRs.

Various fixes 20180328

---

defaults/main.yml
tasks/fix-cat2.yml
tasks/prelim.yml

This improves legibility of the code.
I took the structure names from the "ansible_user_*" fact names.

parse /etc/passwd into data structure

---

.travis.yml
.yamllint
defaults/main.yml
handlers/main.yml
meta/main.yml
tasks/fix-cat1.yml
tasks/fix-cat2.yml
tasks/fix-cat3.yml
tasks/main.yml
tasks/prelim.yml
tests/Dockerfile.centos-7
tests/Dockerfile.rhel-7
tests/apply_role.yml
tests/deregister.yml
tests/extra_vars_travis.yml
tests/extra_vars_vagrant.yml
tests/requirements.yml
tests/role_idempotent_check.yml
tests/test.yml
tests/travis.yml
tests/vagrant_provision.yml
vars/main.yml

I believe this complies with the guidelines here: https://github.com/ansible/ansible-lockdown/blob/master/CONTRIBUTING.md
I left the yamllint defaults mostly in place, only deviating where it made sense.
Please don't squash.

yamllint implementation

---

tasks/fix-cat2.yml

Fix 021000

---

tasks/fix-cat2.yml
tasks/parse_etc_passwd.yml
tasks/prelim.yml

A possible alternative to #110 .

Homedir files owners

---

defaults/main.yml

this version passes both disa and ssg
fixes: #140

update banner to pass benchmarks

---

tasks/fix-cat2.yml

allows this role to run on RHEL 7 Workstation without error

fix repo name for RHEL Workstation

---

tasks/fix-cat1.yml
tasks/fix-cat2.yml
tasks/fix-cat3.yml

followup to #145
also fixes some fatal errors we ran into with assert tasks that should have been debug tasks

Complex rework

---

meta/main.yml

Minor fix for something that is causing Galaxy import to fail

null value in YAML causing issues for Ansible Galaxy import

---

tasks/fix-cat1.yml

fixes #151 
- more friendly output
- don't error out
- speed improvements
- squash bug with setuid files

improve and fix RPM verify

---

defaults/main.yml
tasks/fix-cat2.yml
tasks/parse_etc_passwd.yml

also fix workaround include_tasks not passing tags to included tasks

simplify homedir mode

---

tasks/fix-cat2.yml

Fixes #177 (hopefully; I didn't actually test.)

omit "enablerepo" on non-RHEL yum actions

---

defaults/main.yml
tasks/fix-cat3.yml

RHEL-07-021022 - nodev
RHEL-07-021023 - nosuid
RHEL-07-021024 - noexec /dev/shm mount options

add new cat 3 rules

---

tasks/fix-cat1.yml

fix RHEL-07-010010

---

tasks/audit_command.yml
tasks/audit_file.yml
tasks/audit_system_call.yml
tasks/fix-cat1.yml
tasks/fix-cat2.yml
tasks/fix-cat3.yml

Updates check titles to address the first global task in #174

Title updates

---

tasks/fix-cat2.yml

SSH key mode

---

tasks/fix-cat2.yml
tasks/main.yml

remove requirement to run role with 'gather_facts: yes'

gather necessary facts on demand

---

defaults/main.yml
tasks/fix-cat2.yml
tasks/prelim.yml

trivial change, but reviews required:
```
remote: error: GH006: Protected branch update failed for refs/heads/devel.
remote: error: At least 2 approving reviews are required by reviewers with write access.
To https://github.com/MindPointGroup/RHEL7-STIG.git
! [remote rejected] tag-audit-rules -> devel (protected branch hook declined)
error: failed to push some refs to 'https://github.com/MindPointGroup/RHEL7-STIG.git'
```
(I had to try :P)
Edit: re-using this PR to implement RHEL-07-030200

active=yes in au-remote.conf, tag audit tasks

---

tasks/fix-cat2.yml

RHEL-07-041003
It was a pain in the neck to figure out that regexp, but it works for all the cases I've thrown at it.

pam_pkcs11.conf: cert_policy ocsp_on

---

defaults/main.yml
tasks/fix-cat1.yml
tasks/prelim.yml

RHEL-07-010482 and RHEL-07-010491

grub password for 7.2+

---

tasks/fix-cat2.yml

RhostsRSAAuthentication is obsolete from RHEL 7.4

---

defaults/main.yml
tasks/prelim.yml

automatically detect chroot

---

tasks/fix-cat1.yml
tasks/fix-cat2.yml

mark conditional package removal as disruptive

---

tasks/fix-cat2.yml

authconfig-gtk no longer required

---

tasks/fix-cat3.yml

related #239 
https://vaulted.io/library/disa-stigs-srgs/RHEL_7_STIG?version=V2R2&compareto=V2R3&search=tmp.mount

enable tmp.mount unless /tmp is physical partition

---

tasks/fix-cat2.yml

skip homedir checks for nfsnobody 65534 user

---

tasks/audit_command.yml
tasks/fix-cat2.yml

Remove -F perm=x

---

tasks/fix-cat1.yml

verify system file contents, skip config files

---

defaults/main.yml
handlers/main.yml
tasks/fix-cat2.yml
tasks/fix-cat3.yml
tasks/prelim.yml

Code style cleanup

---

tasks/fix-cat2.yml

openssh-clients not required as of V2R1

---

defaults/main.yml
handlers/main.yml
tasks/fix-cat1.yml
tasks/fix-cat2.yml
tasks/prelim.yml
vars/main.yml

dconf for GUI

---

tasks/fix-cat2.yml

blacklist dccp

---

defaults/main.yml
tasks/fix-cat2.yml

auto-detect presence of compliant screen package -- related #239

allow tmux instead of screen

---

tasks/fix-cat1.yml

Adding support for dracut-fips for Intel CPU with AES instruction support.

Added support for CPU AES instruction for dracut-fips

---

tasks/fix-cat1.yml
tasks/fix-cat2.yml
tasks/fix-cat3.yml

makes it easier to run only pam-related tasks

tag all pam tasks

---

tasks/fix-cat2.yml
tasks/prelim.yml

small fixes found when developing #287

Misc fixes

---

tasks/fix-cat1.yml
tasks/fix-cat2.yml
tasks/prelim.yml

tags gui and dconf tasks

---

doc/README.md
handlers/main.yml
tasks/fix-cat2.yml

Remove variable from output to generic "time service" but keep dynamic internal service restart call.

Fix handler playbook output

---

README.md

updated links and layout

---

README.md

Release 1.0.0 update badge to devel

---

.github/workflows/develtomain.yml
.gitignore

updated workflow and gitignore for devel

---

tasks/fix-cat2.yml

Changes by TrentPetersen04 from PR #344 

Register intend in RHEL-07-040180 | RHEL-07-040190 | RHEL-07-040200 | AUDIT

---

README.md

updated badge for main branch

---

defaults/main.yml

Changed default create_home value from true to yes

---

ChangeLog.md
defaults/main.yml
tasks/fix-cat1.yml
tasks/fix-cat2.yml
tasks/main.yml
tasks/pre_LE_audit.yml

Issue #353  addressed
Syntax and lint improvements

April updates

---

defaults/main.yml
tasks/LE_audit_setup.yml
tasks/pre_LE_audit.yml

Added correct checks for EFI based audit 
merges fixes in  PR #359 due to on going pipeline work

fixed efi check in audit step

---

tasks/fix-cat2.yml

Fix for too much info in perms_results var

---

tasks/fix-cat2.yml

Adjusted 020100 blacklist.conf regex

---

tasks/fix-cat2.yml

sssd.conf permissions #365

---

tasks/fix-cat2.yml

Update main with latest PR's prior to new benchmark release
<mark.bollyuk@gmail.com>

Devel to main for release

---

.github/pull_request_template.md
.gitignore

Added PR template

---

.github/pull_request_template.md

Updated PR template text
None
Updated text in PR template for better information gather and formatting
Please give an overview of how these changes were tested. If they were not please use N/A

Updated PR template text

---

ChangeLog.md
tasks/fix-cat2.yml

Issue fix for not RHEL efi boot servers
changelog update
#385 - efi path fix - Thanks to danbarr

Efi path fix #385

---

ChangeLog.md
meta/main.yml
tasks/fix-cat2.yml

Fix to meta/main.yml to correct repo name
Changelog update
#386 
#385 merged in also

meta update updated as per #386

---

templates/aide.conf.j2

Layout of reporting for aide
#392 
as per PR
Manual

Staging dec21

---

.github/workflows/communitytodevel.yml
.github/workflows/develtomain.yml
tasks/fix-cat2.yml

Updated ami in the workflow 
N/A
N/A
N/A

changed ami

---

tasks/post_remediation_audit.yml

Feedback from discord
Changed title description for audit output - better explain why it would skip some steps
Manually

updated title of audit summary steps

---

.github/workflows/linux_benchmark_testing.yml
.github/workflows/update_galaxy.yml
.yamllint
ChangeLog.md

Updated to meet with galaxy lint requirements
N/A

lint updated inline with galaxy

---

.ansible-lint
.yamllint
README.md
ansible-lint
defaults/main.yml
tasks/fix-cat2.yml
tasks/fix-cat3.yml

Updated both linting files and ran on playbook fixed issues it found with module names.  Also updated the readme file to new standard
N/A
N/A
N/A

Mrsteve linting april 2023, module name update for galaxy score, both lintings passed, update readme file

---

ChangeLog.md
README.md
defaults/main.yml
handlers/main.yml
meta/main.yml
tasks/fix-cat1.yml
tasks/fix-cat2.yml
tasks/main.yml
tasks/prelim.yml
templates/ansible_vars_goss.yml.j2
vars/CentOS.yml
vars/Centos.yml
vars/OracleLinux.yml
vars/RedHat.yml
vars/main.yml

Consistent on ansible version
Improvement in checking ansible user has password 010340
tidy of boootloader discovery and paths
- New controls
- RHEL-07-010019
- RHEL-07-010063
- RHEL-07-020028
- rule id updates and changes
- RHEL-07-010119
- RHEL-07-010199
- RHEL-07-010271
- RHEL-07-020028
- RHEL-07-020030
Manually - working as expected

Stig v3r11 release

---

.ansible-lint
ChangeLog.md
defaults/main.yml
tasks/audit_firewalld.yml
tasks/audit_iptables.yml
tasks/fix-cat2.yml
tasks/main.yml
tasks/prelim.yml
templates/ansible_vars_goss.yml.j2
templates/etc/pam.d/password-auth-local.j2
templates/etc/pam.d/system-auth-local.j2

Stig V3R12 26th July 2023
- RHEL-07-010199 - pamd password and system auth rewrite and ruleid updated
- RHEL-07-010200 - ruleid update
- RHEL_07-010270 - rewritten to align to new settings and ruleid updated - will now skip if 010199
- RHEL_07_020700 - ruleid updated
- RHEL_07_020710 - ruleid updated fixed rule
- RHEL_07_031000 - added new var for log aggregation port default to '@@' =TCP and ruleid updated
- RHEL_07_040300 - ruleid updated
- RHEL_07_040310 - ruleid updated
- RHEL_07_040320 - ruleid updated
- RHEL_07_040340 - ruleid updated
- RHEL-07-010320 & RHEL-07-010330 will now skip if 010199 as this now uses compliant template
Newer lint config added
several linting items updated
Manually

Stig v3r12

---

tasks/pre_remediation_audit.yml

Updated pre-audit setup assert conditional moved to that
this will enable the new workflow
Manually

updated assert for workflow run

---

doc/README.md

Removed the doc directory from legacy information
N/A

removed doc dir

---

tasks/prelim.yml

prelim.yml fixes on when conditions on cronie and passwd_tasks
N/A
N/A
AWS Testing Pipeline

2024 April Update: prelim.yml fixes on when conditions on cronie and passwd_tasks

---

.github/workflows/devel_pipeline_validation.yml
.github/workflows/main_pipeline_validation.yml
.github/workflows/update_galaxy.yml

Updated workflow
